export { EditInstitutionModal } from './edit-institution-modal'
export { DeleteInstitutionModal } from './delete-institution-modal'
export { RegisterInstitutionModal } from './register-institution-modal'
export type { Institution } from './edit-institution-modal'
export type { EditInstitutionModalProps } from './edit-institution-modal'
export type { DeleteInstitutionModalProps } from './delete-institution-modal'
export type { RegisterInstitutionModalProps, RegisterInstitutionFormData } from './register-institution-modal'
